import { Component, OnInit } from '@angular/core';
import { AdminService } from '@haut-spare/data-access-api';
import { Report } from '@haut-spare/data-access-api';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-reports',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="reports-container">
      <div class="reports-header">
        <h2>Reports</h2>
        <button (click)="onGenerateReport()" class="btn-primary">Generate Report</button>
      </div>

      <div *ngIf="loading" class="loading">Loading reports...</div>

      <div *ngIf="!loading && error" class="error-message">
        <p>{{ error }}</p>
        <button (click)="loadReports()">Retry</button>
      </div>

      <table *ngIf="!loading && !error && reports.length > 0" class="reports-table">
        <thead>
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Generated By</th>
            <th>Created</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let report of reports">
            <td>{{ report.title }}</td>
            <td>{{ report.description }}</td>
            <td>{{ report.generatedBy }}</td>
            <td>{{ report.createdAt | date : 'short' }}</td>
            <td>
              <button (click)="onViewReport(report)" class="btn-sm">View</button>
              <button (click)="onDownloadReport(report.id)" class="btn-sm">Download</button>
            </td>
          </tr>
        </tbody>
      </table>

      <div *ngIf="!loading && reports.length === 0" class="empty-state">
        <p>No reports found</p>
      </div>
    </div>
  `,
  styles: [
    `
      .reports-container {
        padding: 20px;
      }

      .reports-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 20px;
      }

      .btn-primary,
      .btn-sm {
        padding: 8px 16px;
        background-color: #007bff;
        color: white;
        border: none;
        border-radius: 4px;
        cursor: pointer;
      }

      .btn-sm {
        padding: 4px 8px;
        font-size: 12px;
        margin-right: 4px;
      }

      .reports-table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
      }

      .reports-table th,
      .reports-table td {
        padding: 12px;
        text-align: left;
        border-bottom: 1px solid #ddd;
      }

      .reports-table th {
        background-color: #f8f9fa;
        font-weight: 600;
      }

      .loading,
      .error-message {
        padding: 20px;
        text-align: center;
      }

      .error-message {
        background-color: #f8d7da;
        color: #721c24;
        border: 1px solid #f5c6cb;
        border-radius: 4px;
      }

      .empty-state {
        text-align: center;
        padding: 40px 20px;
        color: #999;
      }
    `,
  ],
})
export class ReportsComponent implements OnInit {
  reports: Report[] = [];
  loading = false;
  error: string | null = null;

  constructor(private adminService: AdminService) {}

  ngOnInit(): void {
    this.loadReports();
  }

  loadReports(): void {
    this.loading = true;
    this.error = null;

    this.adminService.getReports().subscribe({
      next: (response) => {
        this.reports = response.data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load reports';
        this.loading = false;
        console.error(err);
      },
    });
  }

  onGenerateReport(): void {
    // TODO: Implement generate report dialog
    console.log('Generate report');
  }

  onViewReport(report: Report): void {
    // TODO: Implement view report details
    console.log('View report', report);
  }

  onDownloadReport(reportId: string): void {
    this.adminService.exportReport(reportId, 'pdf').subscribe({
      next: (blob) => {
        // Trigger download
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `report-${reportId}.pdf`;
        a.click();
      },
      error: (err) => {
        console.error('Failed to download report', err);
      },
    });
  }
}
